### ISSUE TITLE
Can't add ZeroPush in Android Studio

### ISSUE THREAD

**Issue by DiegoSBFaria** [ZeroPush/ZeroPush-java#1]
How can we add zero push on Android Studio?

**Comment by smiklosovic** [comment]
Hi @DiegoSBFaria 

You should look at this demo project where ZeroPush SDK is used (1).

If you want to use API from this ZeroPush-java project, you have to put that dependency to build.gradle of your app project like this.

ZeroPush Android SDK is under development.

(1) https://github.com/ZeroPush/ZeroPush-Android-Demo

```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.zeropush:zeropush-android:1.0.0.Alpha1-SNAPSHOT'
    }
}

apply plugin: 'com.android.application'

repositories {
    mavenLocal()
    mavenCentral()
}

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "my.application"
        minSdkVersion 16
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile project(':zeropush-sdk')
    compile 'com.zeropush:zeropush-android:1.0.0.Alpha1-SNAPSHOT'
}
```

**Comment by GantMan** [comment]
Why is the zeropush-sdk separate from the the other gradle options?

I'm using RubyMotion and would love to utilize the `zeropush-sdk` option, but can't really figure out how to include it.   Would be great if it were just a .jar I could include!
